### PR TITLE
Fix concurrent panics and backtraces

### LINKED ISSUE #230: Synchronize dbghelp with the standard library
The dbghelp library on MSVC is not safe to use concurrently from multiple threads. There is no synchronization between the standard library's usage of `RUST_BACKTRACE=1` and this crate generating a backtrace, meaning that it's not technically possible to 100% safely use this crate on MSVC. 

Fixing this will likely require some form of global lock exported by the standard library specifically for backtraces and specifically for MSVC (it can be a noop on all other platforms). This library would then, when compiled on crates.io, need to coordinate with the standard library in terms of locking to ensure that only one implementation is using dbghelp at a time.

### PR DESCRIPTION
**Pull request by alexcrichton**
On Windows `dbghelp.dll` is required to be used from only one thread at
a time, and while this crate provides that guarantee this crate does not
synchronize with itself in the standard library. This commit solves this
issue by using a Windows-specific trick by creating a named mutex for
synchronization.

When this crate is updated in the standard library it means that the
named mutex here will be shared with the standard library, so the
standard library and this crate should be sharing the same
synchronization primitive and should be able to coordinate calls to
`dbghelp.dll`.

More details are included in the commit itself, but this should...

Closes #230

### CODE REVIEW

**Comment by alexcrichton** [comment]
Note that a test was included in https://github.com/rust-lang/backtrace-rs/pull/241, but such a test won't work until we've updated this crate in the standard library itself, so I haven't included the test just yet.

r? @sfackler

File: src/dbghelp.rs [hunk 1]
```diff
@@ -244,45 +244,127 @@ dbghelp! {
...
 }
 
-pub struct Init;
+pub struct Init {
+    lock: HANDLE,
+}
 
-/// Unsafe because this requires external synchronization, must be done
-/// inside of the same lock as all other backtrace operations.
+/// Initialize all supoprt necessary to access `dbghelp` API functions from this
```
Comment (sfackler) [inline src/dbghelp.rs]:
```suggestion
/// Initialize all support necessary to access `dbghelp` API functions from this
```
